In [65]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [111]:
df=pd.read_excel('final_feat.xlsx')

In [112]:
df.head()

Day of week     Cost  Impressions  Clicks     CTR  Avg. CPC  Conversions  \
0    Thursday  3181.56        13361     156  0.0117     20.39        26.77   
1      Friday  2684.67        16841     160  0.0095     16.78        21.00   
2    Saturday  1338.36        30788     142  0.0046      9.43        11.00   
3      Sunday  1192.31        12865     108  0.0084     11.04         5.00   
4      Monday  2383.17        49514     188  0.0038     12.68        22.00   

   Conv. rate  Cost / conv. Search Impr. share  ...  Total Jobs   Avg Service  \
0      0.0486        118.86             0.5337  ...          101   143.417833   
1      0.0299        127.84             0.5477  ...           89    75.515208   
2      0.0186        121.67             0.5297  ...           31   110.019048   
3      0.0130        238.46             0.5741  ...           15    67.914286   
4      0.0566        108.33             0.6027  ...           91    78.753750   

   Avg Install  Canceled Jobs_y  Turn over % Canceled %    Avg Sales  \
0  3224.412750                8     9.900990   7.920792  3617.444828   
1   965.365854                7    10.112360   7.865169  1781.345385   
2  1377.666667                4     9.677419  12.903226   459.248750   
3   406.250000                1    13.333333   6.666667   846.000000   
4  1646.943488                5     8.791209   5.494505  1820.060789   

   bookedjob  totalcalls  Booking rate  
0         49         155     31.612903  
1         56         176     31.818182  
2         30          92     32.608696  
3         11          52     21.153846  
4         54         159     33.962264  

[5 rows x 38 columns]

In [113]:
new_feat=df[['Completed Jobs','Avg Sales','tech_count','TMAX','Income_y']]

In [114]:
new_feat=new_feat.drop_duplicates(ignore_index=True)

In [115]:
new_feat.head()

Completed Jobs    Avg Sales  tech_count  TMAX  Income_y
0              57  3617.444828          59    65  23933.54
1              77  1781.345385          40    71  65232.03
2              55   459.248750          21    69  26195.32
3               6   846.000000           9    69    264.00
4              73  1820.060789          60    77  48506.16

In [116]:
new_feat.head()

Completed Jobs    Avg Sales  tech_count  TMAX  Income_y
0              57  3617.444828          59    65  23933.54
1              77  1781.345385          40    71  65232.03
2              55   459.248750          21    69  26195.32
3               6   846.000000           9    69    264.00
4              73  1820.060789          60    77  48506.16

In [117]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler = MinMaxScaler()


In [170]:
train=new_feat[0:300]
test=new_feat[300:]

In [171]:
y=train['Income_y']
X=train.drop(['Income_y'],axis=1)

In [172]:
X=scaler.fit_transform(X)

In [173]:
y=y.values
y=y.reshape(-1,1)

In [174]:
y=scaler.fit_transform(y)

In [175]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)

In [176]:
from sklearn.svm import SVR
regressor = SVR(kernel ='rbf')
regressor.fit(X_train, y_train)

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [177]:
regressor.score(X_train,y_train)

0.7295645141329945

In [178]:
regressor.score(X_test,y_test)

0.6897631910507167

In [179]:
y_=test['Income_y']
X_=test.drop(['Income_y'],axis=1)

In [180]:
X_=scaler.fit_transform(X_)

In [181]:
y_=y_.values
y_=y_.reshape(-1,1)

In [182]:
y_=scaler.fit_transform(y_)

In [183]:
regressor.score(X_,y_)

0.4294737639874293

In [184]:
from sklearn.model_selection import GridSearchCV

In [185]:
parameters = [{'kernel': ['rbf'], 'gamma': [1e-4, 1e-3, 0.01, 0.1, 0.2, 0.5, 0.6, 0.9],'C': [1, 10, 100, 1000, 10000]}]
print("Tuning hyper-parameters")
svr = GridSearchCV(SVR(epsilon = 0.01), parameters, cv = 5)
svr.fit(X, y)

Tuning hyper-parameters


C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

GridSearchCV(cv=5, estimator=SVR(epsilon=0.01),
             param_grid=[{'C': [1, 10, 100, 1000, 10000],
                          'gamma': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.5, 0.6,
                                    0.9],
                          'kernel': ['rbf']}])

In [186]:
print("Grid scores on training set:")
means = svr.cv_results_['mean_test_score']
stds = svr.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, svr.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r"% (mean, std * 2, params))

Grid scores on training set:
-0.881 (+/-2.291) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
-0.415 (+/-1.509) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.414 (+/-0.301) for {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}
0.545 (+/-0.181) for {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
0.551 (+/-0.185) for {'C': 1, 'gamma': 0.2, 'kernel': 'rbf'}
0.570 (+/-0.198) for {'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}
0.575 (+/-0.202) for {'C': 1, 'gamma': 0.6, 'kernel': 'rbf'}
0.574 (+/-0.217) for {'C': 1, 'gamma': 0.9, 'kernel': 'rbf'}
-0.415 (+/-1.509) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.414 (+/-0.302) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.546 (+/-0.176) for {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
0.564 (+/-0.190) for {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
0.571 (+/-0.210) for {'C': 10, 'gamma': 0.2, 'kernel': 'rbf'}
0.568 (+/-0.246) for {'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}
0.571 (+/-0.251) for {'C': 10, 'gamma': 0.6, 'kernel': 'rbf'}
0.567 (+/-0.254) for {'C': 10, 'ga

In [187]:
# tuning 

tuned_svm = SVR(C=1,gamma=0.6,kernel='rbf')

In [188]:
tuned_svm.fit(X_train,y_train)

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR(C=1, gamma=0.6)

In [189]:
tuned_svm.score(X_train,y_train)

0.6998648261729534

In [190]:
tuned_svm.score(X_test,y_test)

0.7222216513326065

In [191]:
tuned_svm.score(X_,y_)

0.5918751072565033

In [192]:
y_pred_1=tuned_svm.predict(X_)

In [193]:
y_pred_1

array([0.61163644, 0.67894808, 0.60020784, 0.62014651, 0.64334451,
       0.32166084, 0.04839919, 0.47982373, 0.56797968, 0.31282568,
       0.45586032, 0.65744897, 0.65218971, 0.59225955, 0.3430954 ,
       0.64477248, 0.72789091, 0.5172329 , 0.64338869, 0.29239798,
       0.10352124, 0.59145755, 0.6090734 , 0.5475036 , 0.48368218,
       0.24622351, 0.07978988, 0.53348151, 0.61614857, 0.62445087,
       0.47138199, 0.50249012, 0.54036115, 0.19560588, 0.0649536 ,
       0.67426585, 0.69199914, 0.61815825, 0.27060931, 0.09054639,
       0.61855577, 0.64467785, 0.55003073, 0.5228324 ])

In [194]:
y_

array([[0.64538319],
       [0.71801346],
       [0.41174233],
       [0.56530472],
       [0.46708404],
       [0.2080513 ],
       [0.00125798],
       [0.48607213],
       [0.44711839],
       [0.58884186],
       [0.54552699],
       [0.61037564],
       [0.5612979 ],
       [0.43300714],
       [0.38907678],
       [0.72251519],
       [1.        ],
       [0.38532928],
       [0.73490107],
       [0.23433248],
       [0.        ],
       [0.68370481],
       [0.53045481],
       [0.52634861],
       [0.4117368 ],
       [0.35182432],
       [0.2819117 ],
       [0.25485091],
       [0.53767893],
       [0.56721756],
       [0.31376078],
       [0.48683143],
       [0.48683143],
       [0.23259595],
       [0.08846243],
       [0.72688759],
       [0.52620011],
       [0.99625848],
       [0.18273032],
       [0.31024581],
       [0.74977044],
       [0.49877165],
       [0.37240642],
       [0.37780619]])

In [195]:

y_pred_1=y_pred_1.reshape(-1,1)

In [196]:
y_pred_1=scaler.inverse_transform(y_pred_1)

In [197]:
y_pred_1

array([[108550.65940148],
       [120485.51598356],
       [106524.28347037],
       [110059.55835701],
       [114172.73773006],
       [ 57135.81996236],
       [  8684.48839548],
       [ 85179.2809834 ],
       [100809.99016496],
       [ 55569.27953586],
       [ 80930.39085386],
       [116673.5633224 ],
       [115741.05829852],
       [105114.99297929],
       [ 60936.32686198],
       [114425.92744853],
       [129163.44579379],
       [ 91812.20666511],
       [114180.57121981],
       [ 51947.2964206 ],
       [ 18458.03842066],
       [104972.7924499 ],
       [108096.21333653],
       [ 97179.42783444],
       [ 85863.41309034],
       [ 43760.2168171 ],
       [ 14250.29135265],
       [ 94693.2065708 ],
       [109350.69469107],
       [110822.75388871],
       [ 83682.4982991 ],
       [ 89198.20148261],
       [ 95913.01829329],
       [ 34785.33289515],
       [ 11619.70884732],
       [119655.32249364],
       [122799.56660791],
       [109707.02554696],
       [ 480

In [198]:
y_=scaler.inverse_transform(y_)

In [199]:
y_

array([[1.1453421e+05],
       [1.2741210e+05],
       [7.3107940e+04],
       [1.0033570e+05],
       [8.2920440e+04],
       [3.6992000e+04],
       [3.2600000e+02],
       [8.6287170e+04],
       [7.9380380e+04],
       [1.0450901e+05],
       [9.6828960e+04],
       [1.0832711e+05],
       [9.9625260e+04],
       [7.6878350e+04],
       [6.9089170e+04],
       [1.2821029e+05],
       [1.7741042e+05],
       [6.8424710e+04],
       [1.3040640e+05],
       [4.1651850e+04],
       [1.0295000e+02],
       [1.2132892e+05],
       [9.4156550e+04],
       [9.3428490e+04],
       [7.3106960e+04],
       [6.2484030e+04],
       [5.0088000e+04],
       [4.5289920e+04],
       [9.5437440e+04],
       [1.0067486e+05],
       [5.5735080e+04],
       [8.6421800e+04],
       [8.6421800e+04],
       [4.1343950e+04],
       [1.5788000e+04],
       [1.2898555e+05],
       [9.3402160e+04],
       [1.7674702e+05],
       [3.2502400e+04],
       [5.5111850e+04],
       [1.3304285e+05],
       [8.853889

In [200]:
error=y_-y_pred_1

In [201]:
error

array([[  5983.55059852],
       [  6926.58401644],
       [-33416.34347037],
       [ -9723.85835701],
       [-31252.29773006],
       [-20143.81996236],
       [ -8358.48839548],
       [  1107.8890166 ],
       [-21429.61016496],
       [ 48939.73046414],
       [ 15898.56914614],
       [ -8346.4533224 ],
       [-16115.79829852],
       [-28236.64297929],
       [  8152.84313802],
       [ 13784.36255147],
       [ 48246.97420621],
       [-23387.49666511],
       [ 16225.82878019],
       [-10295.4464206 ],
       [-18355.08842066],
       [ 16356.1275501 ],
       [-13939.66333653],
       [ -3750.93783444],
       [-12756.45309034],
       [ 18723.8131829 ],
       [ 35837.70864735],
       [-49403.2865708 ],
       [-13913.25469107],
       [-10147.89388871],
       [-27947.4182991 ],
       [ -2776.40148261],
       [ -9491.21829329],
       [  6558.61710485],
       [  4168.29115268],
       [  9330.22750636],
       [-29397.40660791],
       [ 67039.99445304],
       [-155

-2630.561003444374