In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_excel('final_feat.xlsx')

In [3]:
df.head()

Day of week     Cost  Impressions  Clicks     CTR  Avg. CPC  Conversions  \
0    Thursday  3181.56        13361     156  0.0117     20.39        26.77   
1      Friday  2684.67        16841     160  0.0095     16.78        21.00   
2    Saturday  1338.36        30788     142  0.0046      9.43        11.00   
3      Sunday  1192.31        12865     108  0.0084     11.04         5.00   
4      Monday  2383.17        49514     188  0.0038     12.68        22.00   

   Conv. rate  Cost / conv. Search Impr. share  ...  Total Jobs   Avg Service  \
0      0.0486        118.86             0.5337  ...          101   143.417833   
1      0.0299        127.84             0.5477  ...           89    75.515208   
2      0.0186        121.67             0.5297  ...           31   110.019048   
3      0.0130        238.46             0.5741  ...           15    67.914286   
4      0.0566        108.33             0.6027  ...           91    78.753750   

   Avg Install  Canceled Jobs_y  Turn over % Canceled %    Avg Sales  \
0  3224.412750                8     9.900990   7.920792  3617.444828   
1   965.365854                7    10.112360   7.865169  1781.345385   
2  1377.666667                4     9.677419  12.903226   459.248750   
3   406.250000                1    13.333333   6.666667   846.000000   
4  1646.943488                5     8.791209   5.494505  1820.060789   

   bookedjob  totalcalls  Booking rate  
0         49         155     31.612903  
1         56         176     31.818182  
2         30          92     32.608696  
3         11          52     21.153846  
4         54         159     33.962264  

[5 rows x 38 columns]

In [7]:
df1=df[['Completed Jobs','Avg Sales','tech_count','TMAX','Income_y']]

In [8]:
df1=df1.drop_duplicates(ignore_index=True)

In [9]:
df1.head()

Completed Jobs    Avg Sales  tech_count  TMAX  Income_y
0              57  3617.444828          59    65  23933.54
1              77  1781.345385          40    71  65232.03
2              55   459.248750          21    69  26195.32
3               6   846.000000           9    69    264.00
4              73  1820.060789          60    77  48506.16

In [10]:

df1['f1']=np.sqrt(df1['Completed Jobs']**3)*np.abs(df1['Avg Sales'])
df1['f2']=np.abs(np.sqrt(df1['Completed Jobs']) - np.sqrt(df1['tech_count']))
df1['f3']=np.log(np.sqrt(df1['Completed Jobs'])*df1['TMAX']**3)

In [11]:
df1.head()

Completed Jobs    Avg Sales  tech_count  TMAX  Income_y            f1  \
0              57  3617.444828          59    65  23933.54  1.556733e+06   
1              77  1781.345385          40    71  65232.03  1.203606e+06   
2              55   459.248750          21    69  26195.32  1.873234e+05   
3               6   846.000000           9    69    264.00  1.243361e+04   
4              73  1820.060789          60    77  48506.16  1.135194e+06   

         f2         f3  
0  0.131311  14.544687  
1  2.450409  14.959942  
2  2.833623  14.705986  
3  0.550510  13.598199  
4  0.798037  15.176646

In [12]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler = MinMaxScaler()


In [97]:
df1.columns

Index(['Completed Jobs', 'Avg Sales', 'tech_count', 'TMAX', 'Income_y', 'f1',
       'f2', 'f3'],
      dtype='object')

In [296]:
df2=df1[['Completed Jobs','Income_y', 'f1',
       'f2', 'f3']]

In [297]:
train=df2[0:300]
test=df2[300:]

In [298]:
y=train['Income_y']
X=train.drop(['Income_y'],axis=1)

In [299]:
X=scaler.fit_transform(X)

In [300]:
y=y.values
y=y.reshape(-1,1)

In [301]:
y=scaler.fit_transform(y)

In [302]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)

In [303]:
from sklearn.svm import SVR
regressor = SVR(kernel ='rbf')
regressor.fit(X_train, y_train)

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [304]:
regressor.score(X_train,y_train)

0.7229752457179845

In [305]:
regressor.score(X_test,y_test)

0.7441610195729416

In [306]:
y_=test['Income_y']
X_=test.drop(['Income_y'],axis=1)

In [307]:
X_=scaler.fit_transform(X_)

In [308]:
y_=y_.values
y_=y_.reshape(-1,1)

In [309]:
y_=scaler.fit_transform(y_)

In [310]:
regressor.score(X_,y_)

0.5526870225358365

In [311]:
from sklearn.model_selection import GridSearchCV

In [312]:
parameters = [{'kernel': ['rbf'], 'gamma': [1e-4, 1e-3, 0.01, 0.1, 0.2, 0.5, 0.6, 0.9],'C': [1, 10, 100, 1000, 10000]}]
print("Tuning hyper-parameters")
svr = GridSearchCV(SVR(epsilon = 0.01), parameters, cv = 5)
svr.fit(X, y)

Tuning hyper-parameters


C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**

GridSearchCV(cv=5, estimator=SVR(epsilon=0.01),
             param_grid=[{'C': [1, 10, 100, 1000, 10000],
                          'gamma': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.5, 0.6,
                                    0.9],
                          'kernel': ['rbf']}])

In [313]:
print("Grid scores on training set:")
means = svr.cv_results_['mean_test_score']
stds = svr.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, svr.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r"% (mean, std * 2, params))

Grid scores on training set:
-0.822 (+/-2.164) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
-0.110 (+/-1.046) for {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}
0.554 (+/-0.185) for {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}
0.578 (+/-0.178) for {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
0.580 (+/-0.187) for {'C': 1, 'gamma': 0.2, 'kernel': 'rbf'}
0.579 (+/-0.206) for {'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}
0.580 (+/-0.209) for {'C': 1, 'gamma': 0.6, 'kernel': 'rbf'}
0.575 (+/-0.219) for {'C': 1, 'gamma': 0.9, 'kernel': 'rbf'}
-0.109 (+/-1.046) for {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
0.556 (+/-0.187) for {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}
0.575 (+/-0.176) for {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
0.577 (+/-0.200) for {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
0.574 (+/-0.221) for {'C': 10, 'gamma': 0.2, 'kernel': 'rbf'}
0.571 (+/-0.225) for {'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}
0.568 (+/-0.224) for {'C': 10, 'gamma': 0.6, 'kernel': 'rbf'}
0.558 (+/-0.235) for {'C': 10, 'ga

In [314]:
# tuning 

tuned_svm = SVR(C=1,gamma=0.6,kernel='rbf')

In [315]:
tuned_svm.fit(X_train,y_train)

C:\Users\vksva\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR(C=1, gamma=0.6)

In [316]:
tuned_svm.score(X_train,y_train)

0.7000225803213799

In [317]:
tuned_svm.score(X_test,y_test)

0.7580577385226144

In [318]:
tuned_svm.score(X_,y_)

0.5696550824607529

In [319]:
y_pred_1=tuned_svm.predict(X_)

In [320]:
y_pred_1

array([0.63774907, 0.57793444, 0.51568438, 0.5067314 , 0.68181339,
       0.28232649, 0.05118503, 0.41890896, 0.47875116, 0.26971354,
       0.43605718, 0.61149586, 0.57261127, 0.56712485, 0.33108154,
       0.56199335, 0.69609993, 0.39146163, 0.5514166 , 0.2360863 ,
       0.0899801 , 0.45783931, 0.50311864, 0.47058955, 0.47989843,
       0.26859109, 0.07494872, 0.43838694, 0.5156197 , 0.50812402,
       0.34480821, 0.42633027, 0.42867403, 0.20459245, 0.06286163,
       0.70292937, 0.62653964, 0.50876161, 0.24789286, 0.09436887,
       0.52571589, 0.52963405, 0.41041418, 0.43519835])

In [321]:
y_

array([[0.64538319],
       [0.71801346],
       [0.41174233],
       [0.56530472],
       [0.46708404],
       [0.2080513 ],
       [0.00125798],
       [0.48607213],
       [0.44711839],
       [0.58884186],
       [0.54552699],
       [0.61037564],
       [0.5612979 ],
       [0.43300714],
       [0.38907678],
       [0.72251519],
       [1.        ],
       [0.38532928],
       [0.73490107],
       [0.23433248],
       [0.        ],
       [0.68370481],
       [0.53045481],
       [0.52634861],
       [0.4117368 ],
       [0.35182432],
       [0.2819117 ],
       [0.25485091],
       [0.53767893],
       [0.56721756],
       [0.31376078],
       [0.48683143],
       [0.48683143],
       [0.23259595],
       [0.08846243],
       [0.72688759],
       [0.52620011],
       [0.99625848],
       [0.18273032],
       [0.31024581],
       [0.74977044],
       [0.49877165],
       [0.37240642],
       [0.37780619]])

In [322]:

y_pred_1=y_pred_1.reshape(-1,1)

In [323]:
y_pred_1=scaler.inverse_transform(y_pred_1)

In [324]:
y_pred_1

array([[113180.62414631],
       [102575.04322277],
       [ 91537.64270195],
       [ 89950.21207633],
       [120993.55675548],
       [ 50161.54634726],
       [  9178.43853527],
       [ 74378.63728915],
       [ 84989.10706792],
       [ 47925.17538237],
       [ 77419.1450587 ],
       [108525.73330275],
       [101631.20547318],
       [100658.42244815],
       [ 58806.18051536],
       [ 99748.56840145],
       [123526.66706275],
       [ 69512.0215356 ],
       [ 97873.23238984],
       [ 41962.81458819],
       [ 16057.093142  ],
       [ 81281.27918761],
       [ 89309.64324785],
       [ 83541.99164552],
       [ 85192.5268559 ],
       [ 47726.15620945],
       [ 13391.91813204],
       [ 77832.22872265],
       [ 91526.17471837],
       [ 90197.13402494],
       [ 61240.02095637],
       [ 75694.49142118],
       [ 76110.05722243],
       [ 36378.71926018],
       [ 11248.78685129],
       [124737.57806085],
       [111193.10853194],
       [ 90310.1835316 ],
       [ 440

In [325]:
y_=scaler.inverse_transform(y_)

In [326]:
y_

array([[1.1453421e+05],
       [1.2741210e+05],
       [7.3107940e+04],
       [1.0033570e+05],
       [8.2920440e+04],
       [3.6992000e+04],
       [3.2600000e+02],
       [8.6287170e+04],
       [7.9380380e+04],
       [1.0450901e+05],
       [9.6828960e+04],
       [1.0832711e+05],
       [9.9625260e+04],
       [7.6878350e+04],
       [6.9089170e+04],
       [1.2821029e+05],
       [1.7741042e+05],
       [6.8424710e+04],
       [1.3040640e+05],
       [4.1651850e+04],
       [1.0295000e+02],
       [1.2132892e+05],
       [9.4156550e+04],
       [9.3428490e+04],
       [7.3106960e+04],
       [6.2484030e+04],
       [5.0088000e+04],
       [4.5289920e+04],
       [9.5437440e+04],
       [1.0067486e+05],
       [5.5735080e+04],
       [8.6421800e+04],
       [8.6421800e+04],
       [4.1343950e+04],
       [1.5788000e+04],
       [1.2898555e+05],
       [9.3402160e+04],
       [1.7674702e+05],
       [3.2502400e+04],
       [5.5111850e+04],
       [1.3304285e+05],
       [8.853889

In [327]:
error=y_-y_pred_1

In [328]:
error

array([[  1353.58585369],
       [ 24837.05677723],
       [-18429.70270195],
       [ 10385.48792367],
       [-38073.11675548],
       [-13169.54634726],
       [ -8852.43853527],
       [ 11908.53271085],
       [ -5608.72706792],
       [ 56583.83461763],
       [ 19409.8149413 ],
       [  -198.62330275],
       [ -2005.94547318],
       [-23780.07244815],
       [ 10282.98948464],
       [ 28461.72159855],
       [ 53883.75293725],
       [ -1087.3115356 ],
       [ 32533.16761016],
       [  -310.96458819],
       [-15954.143142  ],
       [ 40047.64081239],
       [  4846.90675215],
       [  9886.49835448],
       [-12085.5668559 ],
       [ 14757.87379055],
       [ 36696.08186796],
       [-32542.30872265],
       [  3911.26528163],
       [ 10477.72597506],
       [ -5504.94095637],
       [ 10727.30857882],
       [ 10311.74277757],
       [  4965.23073982],
       [  4539.21314871],
       [  4247.97193915],
       [-17790.94853194],
       [ 86436.8364684 ],
       [-115

In [329]:
from sklearn import metrics 

In [331]:
np.sqrt(metrics.mean_squared_error(y_,y_pred_1))

25361.263367307463